version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/vol/static
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/vol/static
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  pg_data:
  static_volume: