# Generated by Django 5.2.1 on 2025-05-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
